"""
Module implementing preprocessing defences against adversarial attacks.
"""
from myart.defences.preprocessor.feature_squeezing import FeatureSqueezing
from myart.defences.preprocessor.gaussian_augmentation import GaussianAugmentation
from myart.defences.preprocessor.inverse_gan import DefenseGAN, InverseGAN
from myart.defences.preprocessor.jpeg_compression import JpegCompression
from myart.defences.preprocessor.label_smoothing import LabelSmoothing
from myart.defences.preprocessor.mp3_compression import Mp3Compression
from myart.defences.preprocessor.mp3_compression_pytorch import Mp3CompressionPyTorch
from myart.defences.preprocessor.pixel_defend import PixelDefend
from myart.defences.preprocessor.preprocessor import Preprocessor
from myart.defences.preprocessor.resample import Resample
from myart.defences.preprocessor.spatial_smoothing import SpatialSmoothing
from myart.defences.preprocessor.spatial_smoothing_pytorch import SpatialSmoothingPyTorch
from myart.defences.preprocessor.spatial_smoothing_tensorflow import SpatialSmoothingTensorFlowV2
from myart.defences.preprocessor.thermometer_encoding import ThermometerEncoding
from myart.defences.preprocessor.variance_minimization import TotalVarMin
from myart.defences.preprocessor.video_compression import VideoCompression
from myart.defences.preprocessor.video_compression_pytorch import VideoCompressionPyTorch
